//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 06:59:48 PM BOT 
//


package schemaClasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the schemaClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TemplateTypeNormal_QNAME = new QName("", "normal");
    private final static QName _TemplateTypeMe_QNAME = new QName("", "me");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: schemaClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pcd }
     * 
     */
    public Pcd createPcd() {
        return new Pcd();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link BodyType }
     * 
     */
    public BodyType createBodyType() {
        return new BodyType();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link GradelistType }
     * 
     */
    public GradelistType createGradelistType() {
        return new GradelistType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "normal", scope = TemplateType.class)
    public JAXBElement<String> createTemplateTypeNormal(String value) {
        return new JAXBElement<String>(_TemplateTypeNormal_QNAME, String.class, TemplateType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "me", scope = TemplateType.class)
    public JAXBElement<String> createTemplateTypeMe(String value) {
        return new JAXBElement<String>(_TemplateTypeMe_QNAME, String.class, TemplateType.class, value);
    }

}
